services:
  database-api-wrapper:
    container_name: database-api-wrapper
    environment:
      - SERVICE_CONFIG_APP_NAME=SnackLog
      - SERVICE_CONFIG_API_ROOT_URL=localhost
      - SERVICE_CONFIG_SERVICE_NAME=database-api-wrapper
      - MONGO_INITDB_ROOT_USERNAME=database_api_wrapper
      - MONGO_INITDB_ROOT_PASSWORD=d812d430-de21-413d-9630-47ff5a5b3daa
      - GIN_MODE=debug
    build: .
    ports:
      - 8080:80
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: database_api_wrapper
      MONGO_INITDB_ROOT_PASSWORD: d812d430-de21-413d-9630-47ff5a5b3daa
    volumes:
      - ./openfoodfacts-mongodbdump.gz:/openfoodfacts-mongodbdump.gz:ro
      - ./restore_db.sh:/docker-entrypoint-initdb.d/restore.sh:ro
      - ./data/mongo/:/data/db:rw
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval \"db.adminCommand('ping')\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
